package com.recommendmenu.mechulee.utils

import com.recommendmenu.mechulee.model.data.LicenseInfo

object Constants {
    const val BOTTOM_BAR_STATUS_SHOW = 0
    const val BOTTOM_BAR_STATUS_HIDE = 1

    const val URL_TYPE_MENU = 0
    const val URL_TYPE_INGREDIENT = 1

    const val INTENT_NAME_WEB_URL = "webUrl"
    const val INTENT_NAME_RESULT = "object"

    const val SHARED_PREFERENCES_TUTORIAL_NAME = "tutorial_name"
    const val SHARED_PREFERENCES_TUTORIAL_KEY = "tutorial_key"

    val OPENSOURCE_LICENSE_LIST = arrayListOf(
        LicenseInfo(
            "Lottie\nCopyright 2017 Airbnb, Inc.\nLicensed under the Apache License 2.0",
            "https://github.com/airbnb/lottie-android/blob/master/LICENSE"
        ),
        LicenseInfo(
            "SimpleRatingBar\nCopyright (c) 2019 WilliamYu\nLicensed under the MIT License",
            "https://github.com/williamyyu/SimpleRatingBar/blob/master/LICENSE"
        ),
        LicenseInfo(
            "ExpandableBottomBar\nCopyright (c) 2019 - present, Alexander Dadukin\nLicensed under the MIT License",
            "https://github.com/st235/ExpandableBottomBar/blob/master/LICENSE"
        ),
        LicenseInfo(
            "tag-sphere\nCopyright 2020 Alexander Rychkov\nLicensed under the Apache License 2.0",
            "https://github.com/magic-goop/tag-sphere/blob/master/LICENSE.txt"
        ),
        LicenseInfo(
            "android-map-sdk\nCopyright (c) 2018-2021 NAVER Corp\nLicensed under the Apache License 2.0",
            "https://github.com/navermaps/android-map-sdk/blob/master/LICENSE"
        ),
        LicenseInfo(
            "retrofit\nCopyright 2013 Square, Inc.\nLicensed under the Apache License 2.0",
            "https://github.com/square/retrofit/blob/master/LICENSE.txt"
        ),
        LicenseInfo(
            "glide\nCopyright 2014 Google Inc\nLicensed under the BSD, Apache License 2.0, and MIT license",
            "https://github.com/bumptech/glide/blob/master/LICENSE"
        ),
        LicenseInfo(
            "logger\nCopyright 2018 Orhan Obut\nLicensed under the Apache License 2.0",
            "https://github.com/orhanobut/logger/blob/master/LICENSE"
        ),
        LicenseInfo(
            "CircleImageView\nCopyright 2014 - 2020 Henning Dodenhof\nLicensed under the Apache License 2.0",
            "https://github.com/hdodenhof/CircleImageView/blob/master/LICENSE.txt"
        )
    )

    val MENU_LICENSE_LIST = arrayListOf(
        LicenseInfo("북엇국", "https://www.flickr.com/photos/96349462@N00/564365392") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0/deed.en"),
        LicenseInfo("배추롤", "https://commons.wikimedia.org/wiki/File:Chinese_cabbage_rolls_with_chicken_mince.jpg?uselang=ko") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("콩국수", "https://www.flickr.com/photos/koreanet/27198870013/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("참치김치찌개", "https://www.flickr.com/photos/kfoodaddict/10165987846/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("부대찌개", "https://www.flickr.com/photos/bryansjs/44835481475/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("돼지고기 장조림", "https://www.flickr.com/photos/127584241@N02/15584459417/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("전복죽", "https://www.flickr.com/photos/bryansjs/45749113321/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("야채죽", "https://commons.wikimedia.org/wiki/File:Korean_rice_porridge_Vegetable_juk.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("잔치국수", "https://www.flickr.com/photos/kfoodaddict/7603859406/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("카레덮밥", "https://commons.wikimedia.org/wiki/File:Beef_curry_rice_003.jpg") to LicenseInfo("CC0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("카레우동", "https://commons.wikimedia.org/wiki/File:Curry_udon_by_hirotomo.jpg?uselang=ko") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("야채볶음밥", "https://commons.wikimedia.org/wiki/File:Fried_rice_in_home.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("짜장면", "https://www.flickr.com/photos/stuart_spivack/370040691/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("짬뽕", "https://commons.wikimedia.org/wiki/File:Jjamppong-sujebi_2.jpg?uselang=ko") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("멘보샤", "https://commons.wikimedia.org/wiki/File:Shrimp_toast_from_Tiger's_Cafe_Tuen_Mun.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("삼겹김치볶음밥", "https://pixabay.com/es/photos/arroz-frito-con-kimchi-arroz-frito-241051/") to LicenseInfo("CC0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("치킨볶음밥", "https://commons.wikimedia.org/wiki/File:Siam_Fried_Rice_with_Chicken_by_Papaya,_Hove.jpg") to LicenseInfo("CC0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("닭갈비", "https://www.flickr.com/photos/nagy/17495384/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("소고기 주먹밥", "https://www.flickr.com/photos/cc_photoshare/10958054356/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("탕수욱", "https://commons.wikimedia.org/wiki/File:Tangsuyuk.jpg") to LicenseInfo("CC0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("바지락 칼국수", "https://commons.wikimedia.org/wiki/File:Bajirak-kalguksu_20230126_001.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("장칼국수", "https://commons.wikimedia.org/wiki/File:Jangkalguksu_20220501_001.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("콩나물 불고기", "http://bjbjbjbj.tistory.com/9") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0"),
        LicenseInfo("소불고기", "https://commons.wikimedia.org/wiki/File:Bassak-bulgogi.jpg?uselang=ko") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0"),
        LicenseInfo("차돌숙주볶음", "https://commons.wikimedia.org/wiki/File:Fried_Pork_Bean_Sprout.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("장어구이", "http://ciadfhoz.tistory.com/42") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0"),
        LicenseInfo("삼겹김치찜", "https://commons.wikimedia.org/wiki/File:Mugeun-ji-jjim_1.jpg?uselang=ko") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("뼈해장국", "https://pixabay.com/ko/photos/해장국-국밥-한식-뚝배기-3666599/") to LicenseInfo("CC0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("우거지 감자탕", "https://www.flickr.com/photos/traveloriented/11251558963/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("갈비탕", "https://www.flickr.com/photos/koreanet/16356184153/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("순두부찌개", "https://commons.wikimedia.org/wiki/File:Sundubu-jjigae_2.jpg?uselang=ko") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0"),
        LicenseInfo("돼지갈비", "https://blog.naver.com/deljesu/221111946686") to LicenseInfo("CC BY 2.0 KR", "https://creativecommons.org/licenses/by/2.0/kr/deed.en"),
        LicenseInfo("소갈비", "https://www.flickr.com/photos/68710028@N06/31289696908/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("LA 갈비", "https://commons.wikimedia.org/wiki/File:Korean_BBQ-LA_Galbi-01.jpg?uselang=ko") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("프렌치토스트", "https://www.flickr.com/photos/ruthanddave/10294904906/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("피자토스트", "https://commons.wikimedia.org/wiki/File:Pizza_toast,_at_Gusto.jpg") to LicenseInfo("CC BY-SA 3.0", "https://creativecommons.org/licenses/by-sa/3.0"),
        LicenseInfo("간장치킨", "https://www.flickr.com/photos/97247234@N00/3547603486/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("오므라이스", "https://www.flickr.com/photos/kanesue/50448824236/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("돼지곱창볶음", "https://commons.wikimedia.org/wiki/File:양념곱창.JPG") to LicenseInfo("CC BY-SA 3.0", "https://creativecommons.org/licenses/by-sa/3.0"),
        LicenseInfo("갈치조림", "http://semizzang.tistory.com/4") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0"),

        LicenseInfo("소불고기덮밥", "https://www.flickr.com/photos/kfoodaddict/8634652350/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("꿔바로우", "https://commons.wikimedia.org/wiki/File:Guobaorou_a0.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/deed.en"),
        LicenseInfo("고추잡채", "https://commons.wikimedia.org/wiki/File:Pepper_japchae01.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/deed.en"),
        LicenseInfo("동태전", "https://commons.wikimedia.org/wiki/File:Dongtae-jeon.jpg") to LicenseInfo("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("소고기미역국", "https://commons.wikimedia.org/wiki/File:So-gogi-miyeok-guk_2.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/deed.en"),
        LicenseInfo("고기짬뽕", "https://gongu.copyright.or.kr/gongu/wrt/wrt/view.do?wrtSn=13280167&menuNo=200018") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("냉짬뽕", "https://commons.wikimedia.org/wiki/File:Naeng-jjamppong_3.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/deed.en"),
        LicenseInfo("나가사키짬뽕", "https://commons.wikimedia.org/wiki/File:Oumi_champon_001.jpg") to LicenseInfo("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("에비동", "https://commons.wikimedia.org/wiki/File:Ebidon.JPG") to LicenseInfo("CC BY-SA 3.0", "https://creativecommons.org/licenses/by-sa/3.0/deed.en"),
        LicenseInfo("돈까스김밥", "https://pixabay.com/ko/photos/%ec%9d%8c%ec%8b%9d%ec%82%ac%ec%a7%84-%ed%95%9c%ec%8b%9d-%ea%b9%80%eb%b0%a5-2610864/") to LicenseInfo("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("치즈김밥", "https://commons.wikimedia.org/wiki/File:Cheese_gimbap_and_tuna_gimbap.jpg") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("소고기김밥", "https://commons.wikimedia.org/wiki/File:Gimbap_with_beef,_Myung_Ga_Kimbap.jpg") to LicenseInfo("CC BY-SA 3.0", "https://creativecommons.org/licenses/by-sa/3.0/deed.en"),
        LicenseInfo("선지해장국", "https://www.flickr.com/photos/112024099@N03/22773618778/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("돼지국밥", "https://commons.wikimedia.org/wiki/File:Korean.cuisine-Dwaeji.gukbap-01.jpg") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("순대국밥", "https://krdict.korean.go.kr/eng/dicSearch/viewImageConfirm?nation=eng&searchKindValue=image&ParaWordNo=64870&ParaSenseSeq=1&multiMediaSeq=1") to LicenseInfo("CC BY-SA 2.0 KR", "https://creativecommons.org/licenses/by-sa/2.0/kr/deed.en"),
        LicenseInfo("소내장탕", "https://blog.naver.com/croxriver/130181135385") to LicenseInfo("CC BY 2.0 KR", "https://creativecommons.org/licenses/by/2.0/kr/deed.en"),
        LicenseInfo("콩나물국밥", "https://commons.wikimedia.org/wiki/File:Kongnamul_gukbap_20230408_002.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/deed.en"),
        LicenseInfo("육전", "https://commons.wikimedia.org/wiki/File:Meat_jun.jpg") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("산적꼬치전", "https://www.flickr.com/photos/ramenfuel/4597041843/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("콩나물무침", "https://commons.wikimedia.org/wiki/File:Korean.cuisine-Kongnamul-01.jpg") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("시금치무침", "https://commons.wikimedia.org/wiki/File:%EC%8B%9C%EA%B8%88%EC%B9%98%EB%82%98%EB%AC%BC.JPG") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/deed.en"),
        LicenseInfo("고사리무침", "https://commons.wikimedia.org/wiki/File:Gosari-namul.jpg") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("매운탕", "https://krdict.korean.go.kr/eng/dicSearch/viewImageConfirm?nation=eng&searchKindValue=image&ParaWordNo=55709&ParaSenseSeq=1&multiMediaSeq=2") to LicenseInfo("CC BY-SA 2.0 KR", "https://creativecommons.org/licenses/by-sa/2.0/kr/deed.en"),
        LicenseInfo("달걀국", "https://commons.wikimedia.org/wiki/File:Chinese_gyeran-tang.jpg") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("마라탕", "https://commons.wikimedia.org/wiki/File:Malatang_from_South_Korea.jpg") to LicenseInfo("CC BY 3.0", "https://creativecommons.org/licenses/by/3.0/deed.en"),
        LicenseInfo("마라샹궈", "https://paulcalla.tistory.com/384") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("라조기", "https://nanohora.tistory.com/85") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("깐풍기", "https://www.flickr.com/photos/7828283@N04/2254682782") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("팔보채", "https://tndrnfdl99.tistory.com/129") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("유산슬", "https://commons.wikimedia.org/wiki/File:Yusanseul.jpg") to LicenseInfo("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("양장피", "https://commons.wikimedia.org/wiki/File:Yangjangpi.jpg") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("깐쇼새우", "https://commons.wikimedia.org/wiki/File:Kkansyo-saeu_DSC00978.jpg") to LicenseInfo("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("야끼소바", "https://commons.wikimedia.org/wiki/File:Yakisoba_of_Japan.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/deed.en"),
        LicenseInfo("해물 리조또", "https://commons.wikimedia.org/wiki/File:Cafe_La_Haye_-_2019_August_-_Sarah_Stierch_03.jpg") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("곱창전골", "https://www.flickr.com/photos/fri13th/46826814032/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("버섯전골", "https://commons.wikimedia.org/wiki/File:Mushroom_hot_pot_2.jpg") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("돼지불고기 전골", "https://pixabay.com/ko/photos/%EB%9A%9D%EB%B0%B0%EA%B8%B0-%EB%B6%88%EA%B3%A0%EA%B8%B0-%EB%9A%9D%EB%B0%B0%EA%B8%B0%EB%B6%88%EA%B3%A0%EA%B8%B0-2517765/") to LicenseInfo("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("소불고기 전골", "https://pixabay.com/ko/photos/%EB%B6%88%EA%B3%A0%EA%B8%B0-%EB%B6%88%EA%B3%A0%EA%B8%B0%EC%A0%84%EA%B3%A8-%EB%B6%88%EA%B3%A0%EA%B8%B0%EC%9D%B4%EB%AF%B8%EC%A7%80-1168325/") to LicenseInfo("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("김치전골", "https://www.flickr.com/photos/pelican/3015567106/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0/deed.en"),
        LicenseInfo("닭죽", "https://krdict.korean.go.kr/eng/dicSearch/viewImageConfirm?nation=eng&searchKindValue=image&ParaWordNo=20053&ParaSenseSeq=1&multiMediaSeq=1") to LicenseInfo("CC BY-SA 2.0 KR", "https://creativecommons.org/licenses/by-sa/2.0/kr/deed.en"),
        LicenseInfo("해물라면", "https://www.flickr.com/photos/fri13th/45960262895/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("로제떡볶이", "https://sharphyun.tistory.com/232") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),

        LicenseInfo("닭볶음탕","https://commons.wikimedia.org/wiki/File:13-hadirector1_hoya00571_hoya0057.jpg?uselang=ko") to LicenseInfo("CC0 1.0","https://creativecommons.org/publicdomain/zero/1.0/deed.ko"),
        LicenseInfo("소곱창구이","http://license97.tistory.com/72") to LicenseInfo("CC BY 4.0","https://creativecommons.org/licenses/by/4.0/deed.ko"),
        LicenseInfo("갈치구이","https://www.flickr.com/photos/anokarina/26178319381/") to LicenseInfo("CC BY-SA 2.0","https://creativecommons.org/licenses/by-sa/2.0/deed.ko"),
        LicenseInfo("아귀찜","https://commons.wikimedia.org/wiki/File:Agujjim.jpg?uselang=ko") to LicenseInfo("퍼블릭 도메인","https://ko.wikipedia.org/wiki/%ED%8D%BC%EB%B8%94%EB%A6%AD_%EB%8F%84%EB%A9%94%EC%9D%B8"),
        LicenseInfo("해물찜","https://commons.wikimedia.org/wiki/File:Haemul-jjim.jpg?uselang=ko") to LicenseInfo("CC0 1.0","https://creativecommons.org/publicdomain/zero/1.0/deed.ko"),
        LicenseInfo("쭈꾸미볶음","https://commons.wikimedia.org/wiki/File:Jukkumi-bokkeum.jpg?uselang=ko") to LicenseInfo("CC BY 4.0","https://creativecommons.org/licenses/by/4.0/deed.ko"),
        LicenseInfo("돼지막창구이","https://commons.wikimedia.org/wiki/File:Korean.food-Makchang-04.jpg?uselang=ko") to LicenseInfo("CC BY-SA 2.0","https://creativecommons.org/licenses/by-sa/2.0/deed.ko"),
        LicenseInfo("소막창구이","https://commons.wikimedia.org/wiki/File:Makchang_2.jpg?uselang=ko") to LicenseInfo("CC BY 4.0","https://creativecommons.org/licenses/by/4.0/deed.ko"),
        LicenseInfo("순대볶음","https://commons.wikimedia.org/wiki/File:Sundae-bokkeum.jpg?uselang=ko") to LicenseInfo("CC0 1.0","https://creativecommons.org/publicdomain/zero/1.0/deed.ko"),
        LicenseInfo("간장게장","https://flickr.com/photos/fri13th/46938963914/") to LicenseInfo("CC BY 2.0","https://creativecommons.org/licenses/by/2.0/deed.ko"),
        LicenseInfo("양념게장","https://www.flickr.com/photos/bryansjs/31640602270/") to LicenseInfo("CC BY-SA 2.0","https://creativecommons.org/licenses/by-sa/2.0/deed.ko"),
        LicenseInfo("수제비","https://commons.wikimedia.org/wiki/File:Sujebi.jpg") to LicenseInfo("CC BY-SA 4.0","https://creativecommons.org/licenses/by-sa/4.0/deed.ko"),
        LicenseInfo("차돌박이구이","https://www.flickr.com/photos/fri13th/31933321367/") to LicenseInfo("CC BY 2.0","https://creativecommons.org/licenses/by/2.0/deed.ko"),
        LicenseInfo("간장찜닭","https://www.flickr.com/photos/sunxez/8035488114/") to LicenseInfo("CC BY-SA 2.0","https://creativecommons.org/licenses/by-sa/2.0/deed.ko"),
        LicenseInfo("탕평채","http://ciadfhoz.tistory.com/58") to LicenseInfo("CC BY 4.0","https://creativecommons.org/licenses/by/4.0/deed.ko"),
        LicenseInfo("함박스테이크","https://commons.wikimedia.org/wiki/File:%E3%82%AC%E3%82%B9%E3%83%88%E8%A5%BF%E5%B7%9D%E5%8F%A3%E9%A7%85%E5%89%8D%E5%BA%97%E3%81%AE%E3%83%97%E3%83%AC%E3%83%9F%E3%82%A2%E3%83%A0%E3%83%81%E3%83%BC%E3%82%BA%E3%82%A4%E3%83%B3%E3%83%8F%E3%83%B3%E3%83%90%E3%83%BC%E3%82%B0(20201206).jpg?uselang=ko") to LicenseInfo("CC BY-SA 4.0","https://creativecommons.org/licenses/by-sa/4.0/deed.ko"),
        LicenseInfo("소고기야채죽","https://commons.wikimedia.org/wiki/File:Korean_rice_porridge_Vegetable_juk.jpg?uselang=ko") to LicenseInfo("CC BY-SA 4.0","https://creativecommons.org/licenses/by-sa/4.0/deed.ko"),
        LicenseInfo("들깨칼국수","https://www.flickr.com/photos/eekim/5145990875/") to LicenseInfo("CC BY 2.0","https://creativecommons.org/licenses/by/2.0/deed.ko"),
        LicenseInfo("비빔냉면","https://www.flickr.com/photos/112024099@N03/36236473715/") to LicenseInfo("CC BY 2.0","https://creativecommons.org/licenses/by/2.0/deed.ko"),
        LicenseInfo("물냉면","https://commons.wikimedia.org/wiki/File:Korean_cuisine-Naengmyeon_(Anseong).jpg?uselang=ko") to LicenseInfo("CC BY-SA 3.0","https://creativecommons.org/licenses/by-sa/3.0/deed.ko"),
        LicenseInfo("골뱅이무침","https://commons.wikimedia.org/wiki/File:Golbaengi-muchim.jpg?uselang=ko") to LicenseInfo("CC BY 2.0 KR","https://creativecommons.org/licenses/by/2.0/kr/deed.ko"),
        LicenseInfo("너비아니구이","https://krdict.korean.go.kr/eng/dicSearch/viewImageConfirm?nation=eng&searchKindValue=image&ParaWordNo=42373&ParaSenseSeq=1&multiMediaSeq=1") to LicenseInfo("CC BY-SA 2.0","https://creativecommons.org/licenses/by-sa/2.0/kr/deed.ko"),
        LicenseInfo("비빔국수","https://pixabay.com/photo-709606/") to LicenseInfo("CC0 1.0","https://creativecommons.org/publicdomain/zero/1.0/deed.ko"),
        LicenseInfo("부추전","https://e99ran.tistory.com/20") to LicenseInfo("CC BY 4.0","https://creativecommons.org/licenses/by/4.0/deed.ko"),
        LicenseInfo("부추무침","http://donza.net/69") to LicenseInfo("CC BY 4.0","https://creativecommons.org/licenses/by/4.0/deed.ko"),
        LicenseInfo("꽃게탕","https://commons.wikimedia.org/wiki/File:Korean_crab_hot_pot-01.jpg?uselang=ko") to LicenseInfo("CC BY 2.0","https://creativecommons.org/licenses/by/2.0/deed.ko"),
        LicenseInfo("소고기 뭇국","http://krdict.korean.go.kr/eng/dicSearch/viewImageConfirm?nation=eng&searchKindValue=image&ParaWordNo=28089&ParaSenseSeq=1&multiMediaSeq=1") to LicenseInfo("CC BY-SA 2.0 KR","https://creativecommons.org/licenses/by-sa/2.0/kr/deed.ko"),
        LicenseInfo("토마토 달걀볶음","https://commons.wikimedia.org/wiki/File:%E7%95%AA%E8%8C%84%E7%82%92%E8%9B%8B2.PNG?uselang=ko") to LicenseInfo("CC BY-SA 4.0","https://creativecommons.org/licenses/by-sa/4.0/deed.ko"),
        LicenseInfo("진미채볶음","http://honeysyrup.tistory.com/37") to LicenseInfo("CC BY 4.0","https://creativecommons.org/licenses/by/4.0/deed.ko"),
        LicenseInfo("막국수","https://flickr.com/photos/fri13th/32713065557/") to LicenseInfo("CC BY 2.0","https://creativecommons.org/licenses/by/2.0/deed.ko"),
        LicenseInfo("고기국수","https://commons.wikimedia.org/wiki/File:Gogiguksu_gulmak.jpg?uselang=ko") to LicenseInfo("CC BY-SA 3.0","https://creativecommons.org/licenses/by-sa/3.0/deed.ko"),
        LicenseInfo("김치말이국수","https://www.flickr.com/photos/68147320@N02/48059961688/") to LicenseInfo("CC BY 2.0","https://creativecommons.org/licenses/by/2.0/deed.ko"),
        LicenseInfo("닭칼국수","https://commons.wikimedia.org/wiki/File:%EB%8B%AD%EC%B9%BC%EA%B5%AD%EC%88%98.jpg?uselang=ko") to LicenseInfo("CC BY-SA 3.0","https://creativecommons.org/licenses/by-sa/3.0/deed.ko"),
        LicenseInfo("팥칼국수","https://commons.wikimedia.org/wiki/File:Pat-kal-guksu.jpg?uselang=ko") to LicenseInfo("CC0 1.0","https://creativecommons.org/publicdomain/zero/1.0/deed.ko"),
        LicenseInfo("닭개장","https://commons.wikimedia.org/wiki/File:Dakgaejang.jpg?uselang=ko") to LicenseInfo("CC BY 4.0","https://creativecommons.org/licenses/by/4.0/deed.ko"),
        LicenseInfo("납작만두","http://info.daegu.go.kr/newshome/mtnmain.php?mtnkey=articleview&mkey=scatelist&mkey2=6&aid=232971&bpage=1&stext=") to LicenseInfo("CC BY 4.0","https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("매운돼지갈비찜","https://pixabay.com/photo-1933554/") to LicenseInfo("CC0 1.0","https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        )

    val INGREDIENT_LICENSE_LIST = arrayListOf(
        LicenseInfo("상추 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/lettuce_5346093?term=상추&page=1&position=13&origin=search&related_id=5346093"),
        LicenseInfo("고기 아이콘 제작자: DinosoftLabs - Flaticon", "https://www.flaticon.com/kr/free-icon/beef_3143643?term=소고기&page=1&position=1&origin=search&related_id=3143643"),
        LicenseInfo("버섯 아이콘 제작자: popo2021 - Flaticon", "https://www.flaticon.com/kr/free-icon/mushroom_8886168?term=버섯&page=1&position=4&origin=search&related_id=8886168"),
        LicenseInfo("양고기 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/lamb_4366625?term=양고기&page=1&position=2&origin=search&related_id=4366625"),
        LicenseInfo("케첩 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/ketchup_877824?term=케첩&page=1&position=3&origin=search&related_id=877824"),
        LicenseInfo("소시지 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/sausage_1857881?term=소시지&page=1&position=2&origin=search&related_id=1857881"),
        LicenseInfo("젤리 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/jelly_184579?term=젤리&page=1&position=15&origin=search&related_id=184579"),
        LicenseInfo("고기 아이콘 제작자: Good Ware - Flaticon", "https://www.flaticon.com/kr/free-icon/bacon_5017711?term=고기&page=1&position=16&origin=search&related_id=5017711"),
        LicenseInfo("우유 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/milk_372973?term=우유&page=1&position=3&origin=search&related_id=372973"),
        LicenseInfo("양배추 아이콘 제작자: dDara - Flaticon", "https://www.flaticon.com/kr/free-icon/cabbage_3823331?term=양배추&page=1&position=6&origin=search&related_id=3823331"),
        LicenseInfo("과일 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/cucumber_381083?term=오이&page=1&position=2&origin=search&related_id=381083"),
        LicenseInfo("떡 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/mochi_3362017?term=떡&page=1&position=1&origin=search&related_id=3362017"),
        LicenseInfo("팥 아이콘 제작자: justicon - Flaticon", "https://www.flaticon.com/kr/free-icon/red-beans_2079285?term=팥&page=1&position=2&origin=search&related_id=2079285"),
        LicenseInfo("새우 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/shrimp_2346897?term=새우&page=1&position=1&origin=search&related_id=2346897"),
        LicenseInfo("오리 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/peking-duck_3846159?term=오리&page=1&position=66&origin=search&related_id=3846159"),
        LicenseInfo("쉘 링크 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/sea-snail_616473?term=달팽이&page=1&position=10&origin=search&related_id=616473"),
        LicenseInfo("김치 아이콘 제작자: Flat Icons - Flaticon", "https://www.flaticon.com/kr/free-icon/kimchi_4727309?term=김치&page=1&position=2&origin=search&related_id=4727309"),
        LicenseInfo("음식과 식당 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/spinach_8411072?term=시금치&page=1&position=62&origin=search&related_id=8411072"),
        LicenseInfo("카레 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/curry_510096?term=카레&page=1&position=6&origin=search&related_id=510096"),
        LicenseInfo("오징어 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/squid_616495?term=오징어&page=1&position=10&origin=search&related_id=616495"),
        LicenseInfo("햄 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/ham_1699238?term=햄&page=1&position=1&origin=search&related_id=1699238"),
        LicenseInfo("물고기 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/fish_7584210?term=생선&page=1&position=3&origin=search&related_id=7584210"),
        LicenseInfo("물고기 아이콘 제작자: surang - Flaticon", "https://www.flaticon.com/kr/free-icon/fish_6192106?term=생선&page=1&position=5&origin=search&related_id=6192106"),
        LicenseInfo("과일 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/apple_415733?term=사과&page=1&position=1&origin=search&related_id=415733"),
        LicenseInfo("고기 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/chicken_8119002?term=닭&page=1&position=9&origin=search&related_id=8119002"),
        LicenseInfo("토마토 아이콘 제작자: Rudiyana - Flaticon", "https://www.flaticon.com/kr/free-icon/tomato_2662082?term=토마토&page=1&position=4&origin=search&related_id=2662082"),
        LicenseInfo("라자냐 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/lasagna_8512358?term=라자냐&page=1&position=5&origin=search&related_id=8512358"),
        LicenseInfo("고구마 아이콘 제작자: Mihimihi - Flaticon", "https://www.flaticon.com/kr/free-icon/sweet-potato_8907579?term=고구마&page=1&position=2&origin=search&related_id=8907579"),
        LicenseInfo("쌀 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/rice_7219927?term=쌀&page=1&position=32&origin=search&related_id=7219927"),
        LicenseInfo("중국말 아이콘 제작자: ultimatearm - Flaticon", "https://www.flaticon.com/kr/free-icon/buns_2548242?term=만두&page=1&position=2&origin=search&related_id=2548242"),
        LicenseInfo("멸치 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/anchovy_2056046?term=멸치&page=1&position=4&origin=search&related_id=2056046"),
        LicenseInfo("Anise icons created by Smashicons - Flaticon", "https://www.flaticon.com/free-icon/anise_3006137?term=star+anise&page=1&position=2&origin=search&related_id=3006137"),
        LicenseInfo("두부 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/fried-tofu-curd-balls_890112?related_id=890061&origin=search"),
        LicenseInfo("호박 아이콘 제작자: popo2021 - Flaticon", "https://www.flaticon.com/kr/free-icon/pumpkin_8886190?related_id=8886190"),
        LicenseInfo("돼지 아이콘 제작자: iconixarPro - Flaticon", "https://www.flaticon.com/kr/free-icon/pork_10851752?term=돼지고기&page=1&position=7&origin=search&related_id=10851752"),
        LicenseInfo("야채 아이콘 제작자: max.icons - Flaticon", "https://www.flaticon.com/kr/free-icon/vegetable_3944142?related_id=3944152&origin=search"),
        LicenseInfo("Seaweed icons created by Kise1ki - Flaticon", "https://www.flaticon.com/free-icon/seaweed_9925449?term=seaweed&related_id=9925449"),
        LicenseInfo("소스 아이콘 제작자: Ina Mella - Flaticon", "https://www.flaticon.com/kr/free-icon/sauce_7327731?term=소스&page=2&position=1&origin=search&related_id=7327731"),
        LicenseInfo("소고기 아이콘 제작자: flatart_icons - Flaticon", "https://www.flaticon.com/kr/free-icon/beef_2888560?term=소고기&page=1&position=16&origin=search&related_id=2888560"),
        LicenseInfo("파프리카 아이콘 제작자: Sophia tkx - Flaticon", "https://www.flaticon.com/kr/free-icon/paprika_7830662?term=파프리카&page=1&position=12&origin=search&related_id=7830662"),
        LicenseInfo("메밀 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/buckwheat_6534002?term=메밀&page=1&position=3&origin=search&related_id=6534002"),
        LicenseInfo("Octopus icons created by Amethyst prime - Flaticon", "https://www.flaticon.com/free-icon/octopus_7591558?term=octopus&related_id=7591558"),
        LicenseInfo("해초 아이콘 제작자: dDara - Flaticon", "https://www.flaticon.com/kr/free-icon/seaweed_10806517?related_id=10806588&origin=search"),
        LicenseInfo("고등어 아이콘 제작자: surang - Flaticon", "https://www.flaticon.com/kr/free-icon/mackerel_2884977?term=고등어&page=1&position=2&origin=search&related_id=2884977"),
        LicenseInfo("우동 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/udon_3978738?term=우동&page=1&position=2&origin=search&related_id=3978738"),
        LicenseInfo("갈비 살 아이콘 제작자: kerismaker - Flaticon", "https://www.flaticon.com/kr/free-icon/ribs_5371522?term=갈비&page=1&position=5&origin=search&related_id=5371522"),
        LicenseInfo("인삼 아이콘 제작자: surang - Flaticon", "https://www.flaticon.com/kr/free-icon/ginseng_5789145?term=인삼&page=1&position=9&origin=search&related_id=5789145"),
        LicenseInfo("한국어 아이콘 제작자: surang - Flaticon", "https://www.flaticon.com/kr/free-icon/spice_5789155?term=고추&related_id=5789155"),

        LicenseInfo("양배추 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/cabbage_6108489"),
        LicenseInfo("바베큐 소스 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/bbq-sauce_4214161"),
        LicenseInfo("라면 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/noodles_1046799"),
        LicenseInfo("소장 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/small-intestine_8847711"),
        LicenseInfo("두부 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/tofu_4909053"),
        LicenseInfo("물고기 아이콘 제작자: Flat Icons - Flaticon", "https://www.flaticon.com/kr/free-icon/anglerfish_7751153"),
        LicenseInfo("호박 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/pumpkin_751118"),
        LicenseInfo("어묵 아이콘 제작자: Nhor Phai - Flaticon", "https://www.flaticon.com/kr/free-icon/fish-cake_2090187"),
        LicenseInfo("아스파라거스 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/asparagus_1515027"),
        LicenseInfo("고기 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/chicken_8119002"),
        LicenseInfo("홍합 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/mussel_4391736"),
        LicenseInfo("중국 음식 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/wonton-noodles_890094"),
        LicenseInfo("문어 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/octopus_2339918"),
        LicenseInfo("문어 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/octopus_3751380"),
        LicenseInfo("야자 나무 잎 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/tropical-leaves_7409124"),
        LicenseInfo("튀긴 두부 두부 공 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/fried-tofu-curd-balls_3846212"),
        LicenseInfo("조류 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/seaweed_4515998"),
        LicenseInfo("양파 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/green-onion_4139321"),
        LicenseInfo("마요네즈 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/mayonnaise_4212894"),
        LicenseInfo("가리비 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/scallop_11637383"),
        LicenseInfo("물고기 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/sardines_4374396"),
        LicenseInfo("푸실리 아이콘 제작자: Smashicons - Flaticon", "https://www.flaticon.com/kr/free-icon/fusilli_4714071"),
        LicenseInfo("국자 아이콘 제작자: Smashicons - Flaticon", "https://www.flaticon.com/kr/free-icon/measuring-cup_4257381"),
        LicenseInfo("야채 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/vegetables_5346481"),
        LicenseInfo("가지 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/eggplant_590780"),
        LicenseInfo("죽순 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/bamboo-shoots_5928848"),
        LicenseInfo("참치 아이콘 제작자: smashingstocks - Flaticon", "https://www.flaticon.com/kr/free-icon/canned-food_5371168"),
        LicenseInfo("콩 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/edamame_2314725"),
        LicenseInfo("뱀장어 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/eel_1717857"),
        LicenseInfo("마늘 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/garlic_4004807"),
        LicenseInfo("말린 생선 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/dried-fish_5290322"),
        LicenseInfo("후추 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/chili_2156631"),
        LicenseInfo("잎 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/leaf_7105141"),
        LicenseInfo("소장 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/small-intestine_8847711"),
        LicenseInfo("목재 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/wood_4906933"),
        LicenseInfo("해물 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/seafood_11642708"),
        LicenseInfo("늑골 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/ribs_878608"),
        LicenseInfo("라면 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/noodles_837569"),
        LicenseInfo("칠리 소스 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/hot-sauce_3938958"),
        LicenseInfo("옥수수 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/corn_1652066"),
        LicenseInfo("물고기 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/fish_869473"),
        LicenseInfo("감자 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/potato_1652077"),
        LicenseInfo("배턴 스틱 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/baton_10435660"),
        LicenseInfo("고기 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/ribs_953104"),
        LicenseInfo("올리브유 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/olive-oil_4264699"),
        LicenseInfo("올리브 나무 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/olives_5443112"),
        LicenseInfo("계란 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/egg_2268874"),
        LicenseInfo("닭고기 가슴살 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/chicken-breast_9920991"),
        LicenseInfo("청경채 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/bok-choy_4464809"),
        LicenseInfo("돼지 고기 아이콘 제작자: pojok d - Flaticon", "https://www.flaticon.com/kr/free-icon/pork-ham_3887907"),

        LicenseInfo("Shellfish icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/animals_1759136?term=shellfish&page=1&position=8&origin=search&related_id=1759136"),
        LicenseInfo("Whip cream icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/whip-cream_5816136?term=cream&page=1&position=18&origin=search&related_id=5816136"),
        LicenseInfo("Onion icons created by AngDiz - Flaticon", "https://www.flaticon.com/free-icon/onion_5194898?term=onion&page=1&position=11&origin=search&related_id=5194898"),
        LicenseInfo("Shellfish icons created by AmethystDesign - Flaticon", "https://www.flaticon.com/free-icon/shellfish_5042258?term=shellfish&page=1&position=11&origin=search&related_id=5042258"),
        LicenseInfo("Tofu icons created by mnauliady - Flaticon", "https://www.flaticon.com/free-icon/tofu_7473041?term=tofu&page=1&position=4&origin=search&related_id=7473041"),
        LicenseInfo("Butter icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/butter_3348081?term=butter&page=1&position=47&origin=search&related_id=3348081"),
        LicenseInfo("Lobster icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/lobster_468392?term=lobster&page=1&position=5&origin=search&related_id=468392"),
        LicenseInfo("Soybean icons created by amonrat rungreangfangsai - Flaticon", "https://www.flaticon.com/free-icon/soybean_3183446?term=soybean&page=1&position=57&origin=search&related_id=3183446"),
        LicenseInfo("가자미 아이콘  제작자: Vitaly Gorbachev - Flaticon", "https://www.flaticon.com/kr/free-icon/flounder_7593103?term=%EA%B0%80%EC%9E%90%EB%AF%B8&page=1&position=6&origin=search&related_id=7593103"),
        LicenseInfo("Crab icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/crab_1795594?term=crab&page=1&position=4&origin=search&related_id=1795594"),
        LicenseInfo("Basil icons created by Talha Dogar - Flaticon", "https://www.flaticon.com/free-icon/basil_8154152?term=basil&page=1&position=12&origin=search&related_id=8154152"),
        LicenseInfo("Garlic icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/garlic_4139327?term=garlic&page=1&position=8&origin=search&related_id=4139327"),
        LicenseInfo("Mushroom icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/mushroom_1515022?term=mushroom&page=1&position=10&origin=search&related_id=1515022"),
        LicenseInfo("Zoology icons created by Icongeek26 - Flaticon", "https://www.flaticon.com/free-icon/pollock_7590675?term=pollock&page=1&position=1&origin=search&related_id=7590675"),
        LicenseInfo("Chestnut icons created by Smashicons - Flaticon", "https://www.flaticon.com/free-icon/chestnut_3534795?term=chestnut&page=1&position=3&origin=search&related_id=3534795"),
        LicenseInfo("Bowl icons created by Payungkead - Flaticon", "https://www.flaticon.com/free-icon/noodles_1847158?term=rice+noodle&page=1&position=6&origin=search&related_id=1847158"),
        LicenseInfo("Scoop icons created by Smashicons - Flaticon", "https://www.flaticon.com/free-icon/measuring-cup_4257381?term=powder&related_id=4257381"),
        LicenseInfo("Bread icons created by smashingstocks - Flaticon", "https://www.flaticon.com/free-icon/baguette_7522555?term=bread&page=1&position=14&origin=search&related_id=7522555"),
        LicenseInfo("Ribs icons created by surang - Flaticon", "https://www.flaticon.com/free-icon/ribs_6332512?term=pork+rib&page=1&position=1&origin=search&related_id=6332512"),
        LicenseInfo("Bean sprouts icons created by Yuluck - Flaticon", "https://www.flaticon.com/free-icon/bean-sprouts_11178255?term=bean+sprouts&page=1&position=6&origin=search&related_id=11178255"),
        LicenseInfo("Green beans icons created by imaginationlol - Flaticon", "https://www.flaticon.com/free-icon/beans_6113425?term=green+bean&page=1&position=4&origin=search&related_id=6113425"),
        LicenseInfo("Salmon icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/salmon_9702237?term=salmon&page=1&position=6&origin=search&related_id=9702237"),
        LicenseInfo("Seafood icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/snow-crab_3978836?term=snow+crab&page=1&position=1&origin=search&related_id=3978836"),
        LicenseInfo("Carrot icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/carrot_2224115?term=carrot&page=1&position=13&origin=search&related_id=2224115"),
        LicenseInfo("Grass icons created by Icongeek26 - Flaticon", "https://www.flaticon.com/free-icon/lemon_4788119?term=grass&page=1&position=40&origin=search&related_id=4788119"),
        LicenseInfo("Green onion icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/onion_7922407?term=green+onion&page=1&position=16&origin=search&related_id=7922407"),
        LicenseInfo("Seaweed icons created by Kise1ki - Flaticon", "https://www.flaticon.com/free-icon/seaweed_9925449?term=seaweed&related_id=9925449"),
        LicenseInfo("Cheese icons created by Good Ware - Flaticon", "https://www.flaticon.com/free-icon/cheese_4063291?term=cheese&page=1&position=1&origin=search&related_id=4063291"),
        LicenseInfo("Soy sauce icons created by AmethystDesign - Flaticon", "https://www.flaticon.com/free-icon/soy-sauce_4809718?term=soy+sauce&page=1&position=9&origin=search&related_id=4809718"),
        LicenseInfo("야채 아이콘  제작자: Icongeek26 - Flaticon", "https://www.flaticon.com/kr/free-icon/bell-pepper_2909814?term=%ED%94%BC%EB%A7%9D&page=1&position=1&origin=search&related_id=2909814"),
        LicenseInfo("Flour icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/flour_9126284?term=flour&page=1&position=10&origin=search&related_id=9126284"),
        LicenseInfo("Chives icons created by Icongeek26 - Flaticon", "https://www.flaticon.com/free-icon/chives_4788064?term=chive&page=1&position=3&origin=search&related_id=4788064"),
        LicenseInfo("Fish eggs icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/fish-eggs_3056114?term=fish+egg&page=1&position=28&origin=search&related_id=3056114"),
        LicenseInfo("Lamb icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/lamb_1703034?term=lamb&page=1&position=10&origin=search&related_id=1703034"),
        LicenseInfo("Radish icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/radish_4178976?term=radish&page=1&position=12&origin=search&related_id=4178976"),
        LicenseInfo("Sprouts icons created by pisces86 - Flaticon", "https://www.flaticon.com/free-icon/sprouts_7855735?term=bean+sprouts&page=1&position=4&origin=search&related_id=7855735"),
        LicenseInfo("Mackerel icons created by surang - Flaticon", "https://www.flaticon.com/free-icon/mackerel_2884977?term=mackerel&page=1&position=2&origin=search&related_id=2884977"),
        LicenseInfo("Pasta icons created by Smashicons - Flaticon", "https://www.flaticon.com/free-icon/pasta_135619?term=spaghetti&page=1&position=8&origin=search&related_id=135619"),
        LicenseInfo("Ramen icons created by Freepik - Flaticon", "https://www.flaticon.com/free-icon/noodles_1046799?term=noodle&page=1&position=29&origin=search&related_id=1046799"),
        LicenseInfo("Meat icons created by Smashicons - Flaticon", "https://www.flaticon.com/free-icon/meat_3390629?term=pork&page=1&position=34&origin=search&related_id=3390629"),
        LicenseInfo("Ginger icons created by max.icons - Flaticon", "https://www.flaticon.com/free-icon/ginger_3944333?term=ginger&page=1&position=8&origin=search&related_id=3944333"),
        LicenseInfo("Pork icons created by Icon Place - Flaticon", "https://www.flaticon.com/free-icon/bacon_8204834?term=bacon&page=1&position=27&origin=search&related_id=8204834"),
        LicenseInfo("Cherry tomato icons created by Icongeek26 - Flaticon", "https://www.flaticon.com/free-icon/cherry-tomato_4977391?term=tomato&page=1&position=31&origin=search&related_id=4977391"),
        LicenseInfo("Mozzarella icons created by Smashicons - Flaticon", "https://www.flaticon.com/free-icon/mozzarella_4714026?term=mozzarella&page=1&position=3&origin=search&related_id=4714026"),
        )
}