package com.recommendmenu.mechulee.utils

import com.recommendmenu.mechulee.model.data.LicenseInfo

object Constants {
    const val BOTTOM_BAR_STATUS_SHOW = 0
    const val BOTTOM_BAR_STATUS_HIDE = 1

    const val URL_TYPE_MENU = 0
    const val URL_TYPE_INGREDIENT = 1

    const val INTENT_NAME_WEB_URL = "webUrl"
    const val INTENT_NAME_RESULT = "object"

    val OPENSOURCE_LICENSE_LIST = arrayListOf(
        LicenseInfo(
            "Lottie\nCopyright 2017 Airbnb, Inc.\nLicensed under the Apache License 2.0",
            "https://github.com/airbnb/lottie-android/blob/master/LICENSE"
        ),
        LicenseInfo(
            "SimpleRatingBar\nCopyright (c) 2019 WilliamYu\nLicensed under the MIT License",
            "https://github.com/williamyyu/SimpleRatingBar/blob/master/LICENSE"
        ),
        LicenseInfo(
            "ExpandableBottomBar\nCopyright (c) 2019 - present, Alexander Dadukin\nLicensed under the MIT License",
            "https://github.com/st235/ExpandableBottomBar/blob/master/LICENSE"
        ),
        LicenseInfo(
            "tag-sphere\nCopyright 2020 Alexander Rychkov\nLicensed under the Apache License 2.0",
            "https://github.com/magic-goop/tag-sphere/blob/master/LICENSE.txt"
        ),
        LicenseInfo(
            "android-map-sdk\nCopyright (c) 2018-2021 NAVER Corp\nLicensed under the Apache License 2.0",
            "https://github.com/navermaps/android-map-sdk/blob/master/LICENSE"
        ),
        LicenseInfo(
            "retrofit\nCopyright 2013 Square, Inc.\nLicensed under the Apache License 2.0",
            "https://github.com/square/retrofit/blob/master/LICENSE.txt"
        ),
        LicenseInfo(
            "glide\nCopyright 2014 Google Inc\nLicensed under the BSD, Apache License 2.0, and MIT license",
            "https://github.com/bumptech/glide/blob/master/LICENSE"
        ),
        LicenseInfo(
            "logger\nCopyright 2018 Orhan Obut\nLicensed under the Apache License 2.0",
            "https://github.com/orhanobut/logger/blob/master/LICENSE"
        ),
        LicenseInfo(
            "CircleImageView\nCopyright 2014 - 2020 Henning Dodenhof\nLicensed under the Apache License 2.0",
            "https://github.com/hdodenhof/CircleImageView/blob/master/LICENSE.txt"
        )
    )

    val MENU_LICENSE_LIST = arrayListOf(
        LicenseInfo("북엇국", "https://www.flickr.com/photos/96349462@N00/564365392") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0/deed.en"),
        LicenseInfo("배추롤", "https://commons.wikimedia.org/wiki/File:Chinese_cabbage_rolls_with_chicken_mince.jpg?uselang=ko") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("콩국수", "https://www.flickr.com/photos/koreanet/27198870013/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("참치김치찌개", "https://www.flickr.com/photos/kfoodaddict/10165987846/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("부대찌개", "https://www.flickr.com/photos/bryansjs/44835481475/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("돼지고기 장조림", "https://www.flickr.com/photos/127584241@N02/15584459417/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("전복죽", "https://www.flickr.com/photos/bryansjs/45749113321/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("야채죽", "https://commons.wikimedia.org/wiki/File:Korean_rice_porridge_Vegetable_juk.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("잔치국수", "https://www.flickr.com/photos/kfoodaddict/7603859406/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("카레덮밥", "https://commons.wikimedia.org/wiki/File:Beef_curry_rice_003.jpg") to LicenseInfo("CC0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("카레우동", "https://commons.wikimedia.org/wiki/File:Curry_udon_by_hirotomo.jpg?uselang=ko") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("야채볶음밥", "https://commons.wikimedia.org/wiki/File:Fried_rice_in_home.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("짜장면", "https://www.flickr.com/photos/stuart_spivack/370040691/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("짬뽕", "https://commons.wikimedia.org/wiki/File:Jjamppong-sujebi_2.jpg?uselang=ko") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("멘보샤", "https://commons.wikimedia.org/wiki/File:Shrimp_toast_from_Tiger's_Cafe_Tuen_Mun.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("삼겹김치볶음밥", "https://pixabay.com/es/photos/arroz-frito-con-kimchi-arroz-frito-241051/") to LicenseInfo("CC0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("치킨볶음밥", "https://commons.wikimedia.org/wiki/File:Siam_Fried_Rice_with_Chicken_by_Papaya,_Hove.jpg") to LicenseInfo("CC0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("닭갈비", "https://www.flickr.com/photos/nagy/17495384/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("소고기 주먹밥", "https://www.flickr.com/photos/cc_photoshare/10958054356/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("탕수욱", "https://commons.wikimedia.org/wiki/File:Tangsuyuk.jpg") to LicenseInfo("CC0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("바지락 칼국수", "https://commons.wikimedia.org/wiki/File:Bajirak-kalguksu_20230126_001.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("장칼국수", "https://commons.wikimedia.org/wiki/File:Jangkalguksu_20220501_001.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("콩나물 불고기", "http://bjbjbjbj.tistory.com/9") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0"),
        LicenseInfo("소불고기", "https://commons.wikimedia.org/wiki/File:Bassak-bulgogi.jpg?uselang=ko") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0"),
        LicenseInfo("차돌숙주볶음", "https://commons.wikimedia.org/wiki/File:Fried_Pork_Bean_Sprout.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("장어구이", "http://ciadfhoz.tistory.com/42") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0"),
        LicenseInfo("삼겹김치찜", "https://commons.wikimedia.org/wiki/File:Mugeun-ji-jjim_1.jpg?uselang=ko") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0"),
        LicenseInfo("뼈해장국", "https://pixabay.com/ko/photos/해장국-국밥-한식-뚝배기-3666599/") to LicenseInfo("CC0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("우거지 감자탕", "https://www.flickr.com/photos/traveloriented/11251558963/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("갈비탕", "https://www.flickr.com/photos/koreanet/16356184153/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("순두부찌개", "https://commons.wikimedia.org/wiki/File:Sundubu-jjigae_2.jpg?uselang=ko") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0"),
        LicenseInfo("돼지갈비", "https://blog.naver.com/deljesu/221111946686") to LicenseInfo("CC BY 2.0 KR", "https://creativecommons.org/licenses/by/2.0/kr/deed.en"),
        LicenseInfo("소갈비", "https://www.flickr.com/photos/68710028@N06/31289696908/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0"),
        LicenseInfo("LA 갈비", "https://commons.wikimedia.org/wiki/File:Korean_BBQ-LA_Galbi-01.jpg?uselang=ko") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("프렌치토스트", "https://www.flickr.com/photos/ruthanddave/10294904906/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("피자토스트", "https://commons.wikimedia.org/wiki/File:Pizza_toast,_at_Gusto.jpg") to LicenseInfo("CC BY-SA 3.0", "https://creativecommons.org/licenses/by-sa/3.0"),
        LicenseInfo("간장치킨", "https://www.flickr.com/photos/97247234@N00/3547603486/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("오므라이스", "https://www.flickr.com/photos/kanesue/50448824236/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0"),
        LicenseInfo("돼지곱창볶음", "https://commons.wikimedia.org/wiki/File:양념곱창.JPG") to LicenseInfo("CC BY-SA 3.0", "https://creativecommons.org/licenses/by-sa/3.0"),
        LicenseInfo("갈치조림", "http://semizzang.tistory.com/4") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0"),

        LicenseInfo("소불고기덮밥", "https://www.flickr.com/photos/kfoodaddict/8634652350/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("꿔바로우", "https://commons.wikimedia.org/wiki/File:Guobaorou_a0.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/deed.en"),
        LicenseInfo("고추잡채", "https://commons.wikimedia.org/wiki/File:Pepper_japchae01.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/deed.en"),
        LicenseInfo("동태전", "https://commons.wikimedia.org/wiki/File:Dongtae-jeon.jpg") to LicenseInfo("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("소고기미역국", "https://commons.wikimedia.org/wiki/File:So-gogi-miyeok-guk_2.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/deed.en"),
        LicenseInfo("고기짬뽕", "https://gongu.copyright.or.kr/gongu/wrt/wrt/view.do?wrtSn=13280167&menuNo=200018") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("냉짬뽕", "https://commons.wikimedia.org/wiki/File:Naeng-jjamppong_3.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/deed.en"),
        LicenseInfo("나가사키짬뽕", "https://commons.wikimedia.org/wiki/File:Oumi_champon_001.jpg") to LicenseInfo("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("에비동", "https://commons.wikimedia.org/wiki/File:Ebidon.JPG") to LicenseInfo("CC BY-SA 3.0", "https://creativecommons.org/licenses/by-sa/3.0/deed.en"),
        LicenseInfo("돈까스김밥", "https://pixabay.com/ko/photos/%ec%9d%8c%ec%8b%9d%ec%82%ac%ec%a7%84-%ed%95%9c%ec%8b%9d-%ea%b9%80%eb%b0%a5-2610864/") to LicenseInfo("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("치즈김밥", "https://commons.wikimedia.org/wiki/File:Cheese_gimbap_and_tuna_gimbap.jpg") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("소고기김밥", "https://commons.wikimedia.org/wiki/File:Gimbap_with_beef,_Myung_Ga_Kimbap.jpg") to LicenseInfo("CC BY-SA 3.0", "https://creativecommons.org/licenses/by-sa/3.0/deed.en"),
        LicenseInfo("선지해장국", "https://www.flickr.com/photos/112024099@N03/22773618778/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("돼지국밥", "https://commons.wikimedia.org/wiki/File:Korean.cuisine-Dwaeji.gukbap-01.jpg") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("순대국밥", "https://krdict.korean.go.kr/eng/dicSearch/viewImageConfirm?nation=eng&searchKindValue=image&ParaWordNo=64870&ParaSenseSeq=1&multiMediaSeq=1") to LicenseInfo("CC BY-SA 2.0 KR", "https://creativecommons.org/licenses/by-sa/2.0/kr/deed.en"),
        LicenseInfo("소내장탕", "https://blog.naver.com/croxriver/130181135385") to LicenseInfo("CC BY 2.0 KR", "https://creativecommons.org/licenses/by/2.0/kr/deed.en"),
        LicenseInfo("콩나물국밥", "https://commons.wikimedia.org/wiki/File:Kongnamul_gukbap_20230408_002.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/deed.en"),
        LicenseInfo("육전", "https://commons.wikimedia.org/wiki/File:Meat_jun.jpg") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("산적꼬치전", "https://www.flickr.com/photos/ramenfuel/4597041843/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("콩나물무침", "https://commons.wikimedia.org/wiki/File:Korean.cuisine-Kongnamul-01.jpg") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("시금치무침", "https://commons.wikimedia.org/wiki/File:%EC%8B%9C%EA%B8%88%EC%B9%98%EB%82%98%EB%AC%BC.JPG") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/deed.en"),
        LicenseInfo("고사리무침", "https://commons.wikimedia.org/wiki/File:Gosari-namul.jpg") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("매운탕", "https://krdict.korean.go.kr/eng/dicSearch/viewImageConfirm?nation=eng&searchKindValue=image&ParaWordNo=55709&ParaSenseSeq=1&multiMediaSeq=2") to LicenseInfo("CC BY-SA 2.0 KR", "https://creativecommons.org/licenses/by-sa/2.0/kr/deed.en"),
        LicenseInfo("달걀국", "https://commons.wikimedia.org/wiki/File:Chinese_gyeran-tang.jpg") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("마라탕", "https://commons.wikimedia.org/wiki/File:Malatang_from_South_Korea.jpg") to LicenseInfo("CC BY 3.0", "https://creativecommons.org/licenses/by/3.0/deed.en"),
        LicenseInfo("마라샹궈", "https://paulcalla.tistory.com/384") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("라조기", "https://nanohora.tistory.com/85") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("깐풍기", "https://www.flickr.com/photos/7828283@N04/2254682782") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("팔보채", "https://tndrnfdl99.tistory.com/129") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("유산슬", "https://commons.wikimedia.org/wiki/File:Yusanseul.jpg") to LicenseInfo("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("양장피", "https://commons.wikimedia.org/wiki/File:Yangjangpi.jpg") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("깐쇼새우", "https://commons.wikimedia.org/wiki/File:Kkansyo-saeu_DSC00978.jpg") to LicenseInfo("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("야끼소바", "https://commons.wikimedia.org/wiki/File:Yakisoba_of_Japan.jpg") to LicenseInfo("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/deed.en"),
        LicenseInfo("해물 리조또", "https://commons.wikimedia.org/wiki/File:Cafe_La_Haye_-_2019_August_-_Sarah_Stierch_03.jpg") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("곱창전골", "https://www.flickr.com/photos/fri13th/46826814032/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("버섯전골", "https://commons.wikimedia.org/wiki/File:Mushroom_hot_pot_2.jpg") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        LicenseInfo("돼지불고기 전골", "https://pixabay.com/ko/photos/%EB%9A%9D%EB%B0%B0%EA%B8%B0-%EB%B6%88%EA%B3%A0%EA%B8%B0-%EB%9A%9D%EB%B0%B0%EA%B8%B0%EB%B6%88%EA%B3%A0%EA%B8%B0-2517765/") to LicenseInfo("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("소불고기 전골", "https://pixabay.com/ko/photos/%EB%B6%88%EA%B3%A0%EA%B8%B0-%EB%B6%88%EA%B3%A0%EA%B8%B0%EC%A0%84%EA%B3%A8-%EB%B6%88%EA%B3%A0%EA%B8%B0%EC%9D%B4%EB%AF%B8%EC%A7%80-1168325/") to LicenseInfo("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/deed.en"),
        LicenseInfo("김치전골", "https://www.flickr.com/photos/pelican/3015567106/") to LicenseInfo("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0/deed.en"),
        LicenseInfo("닭죽", "https://krdict.korean.go.kr/eng/dicSearch/viewImageConfirm?nation=eng&searchKindValue=image&ParaWordNo=20053&ParaSenseSeq=1&multiMediaSeq=1") to LicenseInfo("CC BY-SA 2.0 KR", "https://creativecommons.org/licenses/by-sa/2.0/kr/deed.en"),
        LicenseInfo("해물라면", "https://www.flickr.com/photos/fri13th/45960262895/") to LicenseInfo("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/deed.en"),
        LicenseInfo("로제떡볶이", "https://sharphyun.tistory.com/232") to LicenseInfo("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/deed.en"),
        )

    val INGREDIENT_LICENSE_LIST = arrayListOf(
        LicenseInfo("상추 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/lettuce_5346093?term=상추&page=1&position=13&origin=search&related_id=5346093"),
        LicenseInfo("고기 아이콘 제작자: DinosoftLabs - Flaticon", "https://www.flaticon.com/kr/free-icon/beef_3143643?term=소고기&page=1&position=1&origin=search&related_id=3143643"),
        LicenseInfo("버섯 아이콘 제작자: popo2021 - Flaticon", "https://www.flaticon.com/kr/free-icon/mushroom_8886168?term=버섯&page=1&position=4&origin=search&related_id=8886168"),
        LicenseInfo("양고기 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/lamb_4366625?term=양고기&page=1&position=2&origin=search&related_id=4366625"),
        LicenseInfo("케첩 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/ketchup_877824?term=케첩&page=1&position=3&origin=search&related_id=877824"),
        LicenseInfo("소시지 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/sausage_1857881?term=소시지&page=1&position=2&origin=search&related_id=1857881"),
        LicenseInfo("젤리 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/jelly_184579?term=젤리&page=1&position=15&origin=search&related_id=184579"),
        LicenseInfo("고기 아이콘 제작자: Good Ware - Flaticon", "https://www.flaticon.com/kr/free-icon/bacon_5017711?term=고기&page=1&position=16&origin=search&related_id=5017711"),
        LicenseInfo("우유 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/milk_372973?term=우유&page=1&position=3&origin=search&related_id=372973"),
        LicenseInfo("양배추 아이콘 제작자: dDara - Flaticon", "https://www.flaticon.com/kr/free-icon/cabbage_3823331?term=양배추&page=1&position=6&origin=search&related_id=3823331"),
        LicenseInfo("과일 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/cucumber_381083?term=오이&page=1&position=2&origin=search&related_id=381083"),
        LicenseInfo("떡 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/mochi_3362017?term=떡&page=1&position=1&origin=search&related_id=3362017"),
        LicenseInfo("팥 아이콘 제작자: justicon - Flaticon", "https://www.flaticon.com/kr/free-icon/red-beans_2079285?term=팥&page=1&position=2&origin=search&related_id=2079285"),
        LicenseInfo("새우 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/shrimp_2346897?term=새우&page=1&position=1&origin=search&related_id=2346897"),
        LicenseInfo("오리 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/peking-duck_3846159?term=오리&page=1&position=66&origin=search&related_id=3846159"),
        LicenseInfo("쉘 링크 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/sea-snail_616473?term=달팽이&page=1&position=10&origin=search&related_id=616473"),
        LicenseInfo("김치 아이콘 제작자: Flat Icons - Flaticon", "https://www.flaticon.com/kr/free-icon/kimchi_4727309?term=김치&page=1&position=2&origin=search&related_id=4727309"),
        LicenseInfo("음식과 식당 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/spinach_8411072?term=시금치&page=1&position=62&origin=search&related_id=8411072"),
        LicenseInfo("카레 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/curry_510096?term=카레&page=1&position=6&origin=search&related_id=510096"),
        LicenseInfo("오징어 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/squid_616495?term=오징어&page=1&position=10&origin=search&related_id=616495"),
        LicenseInfo("햄 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/ham_1699238?term=햄&page=1&position=1&origin=search&related_id=1699238"),
        LicenseInfo("물고기 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/fish_7584210?term=생선&page=1&position=3&origin=search&related_id=7584210"),
        LicenseInfo("물고기 아이콘 제작자: surang - Flaticon", "https://www.flaticon.com/kr/free-icon/fish_6192106?term=생선&page=1&position=5&origin=search&related_id=6192106"),
        LicenseInfo("과일 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/apple_415733?term=사과&page=1&position=1&origin=search&related_id=415733"),
        LicenseInfo("고기 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/chicken_8119002?term=닭&page=1&position=9&origin=search&related_id=8119002"),
        LicenseInfo("토마토 아이콘 제작자: Rudiyana - Flaticon", "https://www.flaticon.com/kr/free-icon/tomato_2662082?term=토마토&page=1&position=4&origin=search&related_id=2662082"),
        LicenseInfo("라자냐 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/lasagna_8512358?term=라자냐&page=1&position=5&origin=search&related_id=8512358"),
        LicenseInfo("고구마 아이콘 제작자: Mihimihi - Flaticon", "https://www.flaticon.com/kr/free-icon/sweet-potato_8907579?term=고구마&page=1&position=2&origin=search&related_id=8907579"),
        LicenseInfo("쌀 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/rice_7219927?term=쌀&page=1&position=32&origin=search&related_id=7219927"),
        LicenseInfo("중국말 아이콘 제작자: ultimatearm - Flaticon", "https://www.flaticon.com/kr/free-icon/buns_2548242?term=만두&page=1&position=2&origin=search&related_id=2548242"),
        LicenseInfo("멸치 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/anchovy_2056046?term=멸치&page=1&position=4&origin=search&related_id=2056046"),
        LicenseInfo("Anise icons created by Smashicons - Flaticon", "https://www.flaticon.com/free-icon/anise_3006137?term=star+anise&page=1&position=2&origin=search&related_id=3006137"),
        LicenseInfo("두부 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/fried-tofu-curd-balls_890112?related_id=890061&origin=search"),
        LicenseInfo("호박 아이콘 제작자: popo2021 - Flaticon", "https://www.flaticon.com/kr/free-icon/pumpkin_8886190?related_id=8886190"),
        LicenseInfo("돼지 아이콘 제작자: iconixarPro - Flaticon", "https://www.flaticon.com/kr/free-icon/pork_10851752?term=돼지고기&page=1&position=7&origin=search&related_id=10851752"),
        LicenseInfo("야채 아이콘 제작자: max.icons - Flaticon", "https://www.flaticon.com/kr/free-icon/vegetable_3944142?related_id=3944152&origin=search"),
        LicenseInfo("Seaweed icons created by Kise1ki - Flaticon", "https://www.flaticon.com/free-icon/seaweed_9925449?term=seaweed&related_id=9925449"),
        LicenseInfo("소스 아이콘 제작자: Ina Mella - Flaticon", "https://www.flaticon.com/kr/free-icon/sauce_7327731?term=소스&page=2&position=1&origin=search&related_id=7327731"),
        LicenseInfo("소고기 아이콘 제작자: flatart_icons - Flaticon", "https://www.flaticon.com/kr/free-icon/beef_2888560?term=소고기&page=1&position=16&origin=search&related_id=2888560"),
        LicenseInfo("파프리카 아이콘 제작자: Sophia tkx - Flaticon", "https://www.flaticon.com/kr/free-icon/paprika_7830662?term=파프리카&page=1&position=12&origin=search&related_id=7830662"),
        LicenseInfo("메밀 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/buckwheat_6534002?term=메밀&page=1&position=3&origin=search&related_id=6534002"),
        LicenseInfo("Octopus icons created by Amethyst prime - Flaticon", "https://www.flaticon.com/free-icon/octopus_7591558?term=octopus&related_id=7591558"),
        LicenseInfo("해초 아이콘 제작자: dDara - Flaticon", "https://www.flaticon.com/kr/free-icon/seaweed_10806517?related_id=10806588&origin=search"),
        LicenseInfo("고등어 아이콘 제작자: surang - Flaticon", "https://www.flaticon.com/kr/free-icon/mackerel_2884977?term=고등어&page=1&position=2&origin=search&related_id=2884977"),
        LicenseInfo("우동 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/udon_3978738?term=우동&page=1&position=2&origin=search&related_id=3978738"),
        LicenseInfo("갈비 살 아이콘 제작자: kerismaker - Flaticon", "https://www.flaticon.com/kr/free-icon/ribs_5371522?term=갈비&page=1&position=5&origin=search&related_id=5371522"),
        LicenseInfo("인삼 아이콘 제작자: surang - Flaticon", "https://www.flaticon.com/kr/free-icon/ginseng_5789145?term=인삼&page=1&position=9&origin=search&related_id=5789145"),
        LicenseInfo("한국어 아이콘 제작자: surang - Flaticon", "https://www.flaticon.com/kr/free-icon/spice_5789155?term=고추&related_id=5789155"),

        LicenseInfo("양배추 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/cabbage_6108489"),
        LicenseInfo("바베큐 소스 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/bbq-sauce_4214161"),
        LicenseInfo("라면 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/noodles_1046799"),
        LicenseInfo("소장 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/small-intestine_8847711"),
        LicenseInfo("두부 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/tofu_4909053"),
        LicenseInfo("물고기 아이콘 제작자: Flat Icons - Flaticon", "https://www.flaticon.com/kr/free-icon/anglerfish_7751153"),
        LicenseInfo("호박 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/pumpkin_751118"),
        LicenseInfo("어묵 아이콘 제작자: Nhor Phai - Flaticon", "https://www.flaticon.com/kr/free-icon/fish-cake_2090187"),
        LicenseInfo("아스파라거스 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/asparagus_1515027"),
        LicenseInfo("고기 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/chicken_8119002"),
        LicenseInfo("홍합 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/mussel_4391736"),
        LicenseInfo("중국 음식 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/wonton-noodles_890094"),
        LicenseInfo("문어 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/octopus_2339918"),
        LicenseInfo("문어 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/octopus_3751380"),
        LicenseInfo("야자 나무 잎 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/tropical-leaves_7409124"),
        LicenseInfo("튀긴 두부 두부 공 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/fried-tofu-curd-balls_3846212"),
        LicenseInfo("조류 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/seaweed_4515998"),
        LicenseInfo("양파 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/green-onion_4139321"),
        LicenseInfo("마요네즈 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/mayonnaise_4212894"),
        LicenseInfo("가리비 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/scallop_11637383"),
        LicenseInfo("물고기 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/sardines_4374396"),
        LicenseInfo("푸실리 아이콘 제작자: Smashicons - Flaticon", "https://www.flaticon.com/kr/free-icon/fusilli_4714071"),
        LicenseInfo("국자 아이콘 제작자: Smashicons - Flaticon", "https://www.flaticon.com/kr/free-icon/measuring-cup_4257381"),
        LicenseInfo("야채 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/vegetables_5346481"),
        LicenseInfo("가지 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/eggplant_590780"),
        LicenseInfo("죽순 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/bamboo-shoots_5928848"),
        LicenseInfo("참치 아이콘 제작자: smashingstocks - Flaticon", "https://www.flaticon.com/kr/free-icon/canned-food_5371168"),
        LicenseInfo("콩 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/edamame_2314725"),
        LicenseInfo("뱀장어 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/eel_1717857"),
        LicenseInfo("마늘 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/garlic_4004807"),
        LicenseInfo("말린 생선 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/dried-fish_5290322"),
        LicenseInfo("후추 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/chili_2156631"),
        LicenseInfo("잎 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/leaf_7105141"),
        LicenseInfo("소장 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/small-intestine_8847711"),
        LicenseInfo("목재 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/wood_4906933"),
        LicenseInfo("해물 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/seafood_11642708"),
        LicenseInfo("늑골 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/ribs_878608"),
        LicenseInfo("라면 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/noodles_837569"),
        LicenseInfo("칠리 소스 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/hot-sauce_3938958"),
        LicenseInfo("옥수수 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/corn_1652066"),
        LicenseInfo("물고기 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/fish_869473"),
        LicenseInfo("감자 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/potato_1652077"),
        LicenseInfo("배턴 스틱 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/baton_10435660"),
        LicenseInfo("고기 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/ribs_953104"),
        LicenseInfo("올리브유 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/olive-oil_4264699"),
        LicenseInfo("올리브 나무 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/olives_5443112"),
        LicenseInfo("계란 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/egg_2268874"),
        LicenseInfo("닭고기 가슴살 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/chicken-breast_9920991"),
        LicenseInfo("청경채 아이콘 제작자: Freepik - Flaticon", "https://www.flaticon.com/kr/free-icon/bok-choy_4464809"),
        LicenseInfo("돼지 고기 아이콘 제작자: pojok d - Flaticon", "https://www.flaticon.com/kr/free-icon/pork-ham_3887907"),
        )
}